app_name: "autoc-vizzo-core"
app_name_nix: "autoc-vizzo-core-nix"
namespace: "vizzoo-dev"

apps:
  - name: "{{ app_name }}"
    deploy_name: "{{ app_name }}"
    group: "{{ namespace }}"
    image: "gitlab-dreg.nexxera.com/nexxcard/autoc-vizzoo-core:master"
    cpu:
        min: "10"
        max: "200"
    memory:
        min: "10"
        max: "256"    
    routes:
      - name: "{{ app_name }}-dev"
        hostname: "{{ app_name }}-dev"
        port: "8080"
        path: ""
        certificate: ""
        external: true
    env_vars:
      - VIZZO_URL="https://virtual-account-web-dev.cloudint.nexxera.com"
      - VIZZOO_URL_GET_TOKEN="https://login-int.nexxera.com/auth/realms/vizzoo-dev/protocol/openid-connect/token"
      - VIZZOO_MANAGER_URL="https://vizzoo-core-dev.cloudint.nexxera.com/v1/"
      - VIZZOO_SSO_CLIENT_SECRET="db89b976-fc1f-4b57-a1c1-f68e573210e0"
      - COMMANDER_URL="https://skylineweb-view-dev.cloudint.nexxera.com/skyline-web-gateway/"
      - COMMANDER_USER="Adm_cartoes"
      - COMMANDER_PASS="cartoes2019"
      - GENSKY_URL="https://skyline-manager.cloudint.nexxera.com/skyline-manager-gateway/"
      - GENSKY_USER="appautvizzoo"
      - GENSKY_PASS="Acv1zz00!"
      - NOTIFIER_SENDER="https://api-notification-dispatcher-dev.cloudint.nexxera.com/simple-email"
      - HOST_NAME="oratst.nexxera.com:1521/DEV"
      - HOST_USER="DEV_VIZZOO_CONTRAT"
      - HOST_PASSWORD="ZtySBC62Fa8"
      - ALLOWED_HOSTS="autoc-vizzo-core-dev.cloudint.nexxera.com"
      - CONFIRMAR_DADOS_USUARIO="https://autoc-vizzo-core-dev.cloudint.nexxera.com/autoimplantar/"
      - AUTOCONTRATACAO_URL="https://autoc-vizzo-core-dev.cloudint.nexxera.com/autocontratacao"
      - GATEWAY_URL="https://gateway-nix-qa.cloudint.nexxera.com/v2"
      - GATEWAY_SECRET="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3M2M2ZGI0Yi04NDE0LTRkMjUtYmI1Ni02NDViNWY5NWQyNDkiLCJhY2Nlc3MiOlsiY2FyZFBheW1lbnRzIiwicmVjdXJyZW5jZVBsYW5zIiwicmVjdXJyZW5jZXMiLCJib2xldG9QYXltZW50cyIsImludm9pY2VzIiwiY2hlY2tvdXQiLCJVU0VSLlJFTU9WRUNVU1RPTUVSIl0sImV4cCI6MTYwNTEzNDIxNH0.sHnARp6oQy-nuGMTzBzKZ7STlJKTdS4kpG9X6aS5_F0"
      - GATEWAY_REQUEST_ID="7f11dc3c-2c82-4c66-862a-406622e0770e"

  - name: "{{ app_name_nix }}"
    deploy_name: "{{ app_name_nix }}"
    group: "{{ namespace }}"
    image: "gitlab-dreg.nexxera.com/nexxcard/autoc-vizzoo-core:master"
    cpu:
        min: "10"
        max: "200"
    memory:
        min: "10"
        max: "256"    
    routes:
      - name: "{{ app_name_nix }}-dev"
        hostname: "{{ app_name_nix }}-dev"
        port: "8080"
        path: ""
        certificate: ""
        external: true
    env_vars:
      - VIZZO_URL="https://virtual-account-web-dev.cloudint.nexxera.com"
      - VIZZOO_URL_GET_TOKEN="https://login-int.nexxera.com/auth/realms/vizzoo-dev/protocol/openid-connect/token"
      - VIZZOO_MANAGER_URL="https://vizzoo-core-dev.cloudint.nexxera.com/v1/"
      - VIZZOO_SSO_CLIENT_SECRET="db89b976-fc1f-4b57-a1c1-f68e573210e0"
      - COMMANDER_URL="https://skylineweb-view-dev.cloudint.nexxera.com/skyline-web-gateway/"
      - COMMANDER_USER="Adm_cartoes"
      - COMMANDER_PASS="cartoes2019"
      - GENSKY_URL="https://skyline-manager.cloudint.nexxera.com/skyline-manager-gateway/"
      - GENSKY_USER="appautvizzoo"
      - GENSKY_PASS="Acv1zz00!"
      - NOTIFIER_SENDER="https://api-notification-dispatcher-dev.cloudint.nexxera.com/simple-email"
      - HOST_NAME="oratst.nexxera.com:1521/DEV"
      - HOST_USER="DEV_VIZZOO_CONTRAT_NIX"
      - HOST_PASSWORD="d11#rOL2"
      - ALLOWED_HOSTS="autoc-vizzo-core-nix-dev.cloudint.nexxera.com"
      - CONFIRMAR_DADOS_USUARIO="https://autoc-vizzo-core-nix-dev.cloudint.nexxera.com/autoimplantar/"
      - AUTOCONTRATACAO_URL="https://autoc-vizzo-core-nix-dev.cloudint.nexxera.com/autocontratacao"
      - GATEWAY_URL="https://gateway-nix-qa.cloudint.nexxera.com/v2"
      - GATEWAY_SECRET="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3M2M2ZGI0Yi04NDE0LTRkMjUtYmI1Ni02NDViNWY5NWQyNDkiLCJhY2Nlc3MiOlsiY2FyZFBheW1lbnRzIiwicmVjdXJyZW5jZVBsYW5zIiwicmVjdXJyZW5jZXMiLCJib2xldG9QYXltZW50cyIsImludm9pY2VzIiwiY2hlY2tvdXQiLCJVU0VSLlJFTU9WRUNVU1RPTUVSIl0sImV4cCI6MTYwNTEzNDIxNH0.sHnARp6oQy-nuGMTzBzKZ7STlJKTdS4kpG9X6aS5_F0"
      - GATEWAY_REQUEST_ID="7f11dc3c-2c82-4c66-862a-406622e0770e"
