# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adquirente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.CharField(blank=True, max_length=400, null=True)),
                ('id_ordem', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('fg_arquivo', models.BooleanField()),
                ('fg_email', models.BooleanField()),
                ('fg_site_operadora', models.BooleanField()),
                ('fg_infra_nexx', models.BooleanField()),
                ('layout', models.CharField(blank=True, max_length=100, null=True)),
                ('fg_ativo', models.NullBooleanField()),
            ],
            options={
                'db_table': 'adquirente',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaErros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_erro', models.DateField(blank=True, null=True)),
                ('header', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('dados_json', models.CharField(blank=True, max_length=2000, null=True)),
                ('erro', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'auditoria_erros',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaImplantacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_cadastro', models.DateField(blank=True, null=True)),
                ('dt_ultima_alteracao', models.DateField(blank=True, null=True)),
                ('fg_commander', models.NullBooleanField()),
                ('fg_gensky_caixa_postal', models.NullBooleanField()),
                ('fg_gensky_mascaras', models.NullBooleanField()),
                ('fg_vizzoo_grupo', models.NullBooleanField()),
                ('fg_vizzoo_estabelecimentos', models.NullBooleanField()),
                ('fg_vizzoo_usuario', models.NullBooleanField()),
                ('fg_abertura_relacionamento', models.NullBooleanField()),
            ],
            options={
                'db_table': 'auditoria_implantacao',
            },
        ),
        migrations.CreateModel(
            name='AutoImplantar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('dt_cadastro', models.DateField(blank=True, null=True)),
                ('dt_vencimento', models.DateField(blank=True, null=True)),
                ('hash_liberacao', models.CharField(max_length=255)),
                ('is_implantado', models.NullBooleanField()),
            ],
            options={
                'db_table': 'auto_implantar',
            },
        ),
        migrations.CreateModel(
            name='BlackList_Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('is_ativo', models.NullBooleanField()),
            ],
            options={
                'db_table': 'blacklist_estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('is_vizzoo', models.NullBooleanField()),
            ],
            options={
                'db_table': 'estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_transacao', models.IntegerField(blank=True, null=True)),
                ('valor_fixo', models.FloatField(blank=True, null=True)),
                ('valor_adicional', models.FloatField(blank=True, null=True)),
                ('fg_ativo', models.NullBooleanField()),
            ],
            options={
                'db_table': 'franquia',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('is_vizzoo', models.NullBooleanField()),
                ('nome_caixa_postal', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='GrupoAdquirente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_ativo', models.NullBooleanField()),
                ('adquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacao.Adquirente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacao.Grupo')),
            ],
            options={
                'db_table': 'grupo_adquirente',
            },
        ),
        migrations.CreateModel(
            name='Mascara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caixa_postal', models.IntegerField()),
                ('id_estacao', models.IntegerField()),
                ('mask_banco_entrada', models.CharField(blank=True, max_length=150, null=True)),
                ('mask_banco_saida', models.CharField(blank=True, max_length=150, null=True)),
                ('mask_cliente_entrada', models.CharField(blank=True, max_length=150, null=True)),
                ('mask_cliente_saida', models.CharField(blank=True, max_length=150, null=True)),
                ('mask_envio_email', models.CharField(blank=True, max_length=150, null=True)),
                ('nu_timeout', models.IntegerField()),
                ('horas_iniciais', models.CharField(blank=True, max_length=10, null=True)),
                ('horas_finais', models.CharField(blank=True, max_length=10, null=True)),
                ('script_recepcao_banco', models.CharField(max_length=255)),
                ('script_transmissao_banco', models.CharField(max_length=255)),
                ('script_validacao_cliente', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('reset_cont_diario_rvs_cliente', models.BooleanField()),
                ('herdar_cont_diario_rvs_cliente', models.BooleanField()),
                ('contador_diario_rvs_cliente', models.IntegerField()),
                ('verificar_duplicidade_rvs_cliente', models.BooleanField()),
                ('reset_cont_diario_cliente_rvs', models.BooleanField()),
                ('herdar_cont_diario_cliente_rvs', models.BooleanField()),
                ('contador_diario_cliente_rvs', models.IntegerField()),
                ('opcoes_envio_arquivo', models.IntegerField()),
                ('script_envio', models.CharField(blank=True, max_length=1500, null=True)),
                ('adquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacao.Adquirente')),
            ],
            options={
                'db_table': 'mascara',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('fg_ativo', models.NullBooleanField()),
                ('is_vizzoo', models.NullBooleanField()),
                ('dt_cadastro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='adquirentes',
            field=models.ManyToManyField(through='contratacao.GrupoAdquirente', to='contratacao.Adquirente'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='franquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franquia', to='contratacao.Franquia'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='contratacao.Usuario'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='contratacao.Grupo'),
        ),
        migrations.AddField(
            model_name='autoimplantar',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacao.Grupo'),
        ),
        migrations.AddField(
            model_name='autoimplantar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacao.Usuario'),
        ),
    ]
