# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquia',
            name='merchant_plan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
