# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacao', '0002_franquia_merchant_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPagamento', models.IntegerField(blank=True, null=True)),
                ('numeroPedido', models.CharField(blank=True, max_length=30, null=True)),
                ('tokenPagamento', models.CharField(max_length=50)),
                ('statusPagamento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='PagamentoCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCartaoCredito', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSeguranca', models.CharField(blank=True, max_length=4, null=True)),
                ('dataValidade', models.DateField(blank=True, null=True)),
                ('nomeImpresso', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('tokenPagamento', models.CharField(max_length=50)),
                ('tokenCard', models.CharField(max_length=50)),
                ('statusPagamento', models.IntegerField(blank=True, null=True)),
                ('codigoAutorizacao', models.CharField(max_length=20)),
                ('retornoCodigoAutorizacao', models.CharField(max_length=20)),
                ('bandeira', models.CharField(max_length=30)),
                ('urlRetorno', models.CharField(max_length=2000)),
                ('idCliente', models.BigIntegerField()),
                ('pagamento', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PagamentoCartaoPag', to='contratacao.Pagamento')),
            ],
            options={
                'db_table': 'pagamento_cartao',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='pagamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GrupoPagamento', to='contratacao.Pagamento'),
        ),
    ]
