# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacao', '0004_boletobancario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoletoBancario',
            new_name='PagamentoBoleto',
        ),
        migrations.AddField(
            model_name='grupo',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
