# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-22 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacao', '0006_auto_20191122_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='templateemail',
            table='TEMPLATE_EMAIL',
        ),
    ]
