apps:
  - name: "autocontratacao-vizzoo-web"
    deploy_name: "autocontratacao-vizzoo-web"
    group: "vizzoo-dev"
    image: "gitlab-dreg.nexxera.com/nexxcard/portal-auto-cadastro-vizzoo:master"
    cpu:
        min: "10"
        max: "200"
    memory:
        min: "10"
        max: "128" 
    routes:
      - name: "autocontratacao-vizzoo-web-dev"
        hostname: "autocontratacao-vizzoo-web-dev"
        port: "8000"
        path: ""
        certificate: ""
    env_vars:
      - URL_API='https://autoc-vizzo-core-dev.cloudint.nexxera.com'
      - API_LOGIN='autocontratacao'
      - API_PASSWORD='autocvizzoo!'
      - URL_VIZZO='https://vizzoo-web-app-dev.cloudint.nexxera.com/vizzoo'

